### ISSUE TITLE
torch.AcceleratorError: CUDA error: out of memory

### ISSUE THREAD

**Issue by githubnoobb** [Redtash1/Wan2GP-Windows-One-Click-Install-With-Sage#7]
I'm getting CUDA out of memory errors on v.2.0.0. Sometimes it will generate a few videos and then the error shows, other times it happens immediately. Looking at HWinfo64 it seems to completely fill the RAM, and then spills over to pagefile until it gives the error. It's almost like a memory leak?

- I don't have much experience with this but I did my best to test it properly, each release version I used was a fresh install.
- I installed using the Install_Wan2GP_RTX_40XX_50XX.bat file.
- v1.0.2 had no issues, v2.0.0 is the only release that is creating this issue for me.

PC specs: RTX 5080, 64GB RAM, Windows 11, latest nvidia drivers.

Error shown below:

Traceback (most recent call last):
  File "C:\Wan2GP\wan2gp\wgp.py", line 5278, in generate_video
    samples = wan_model.generate(
  File "C:\Wan2GP\wan2gp\models\wan\any2video.py", line 997, in generate
    ret_values[x_id] = trans( **sub_gen_args, x_id= x_id , **kwargs)[0]
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\mmgp\offload.py", line 2396, in check_change_module
    return previous_method(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\models\wan\modules\model.py", line 1605, in forward
    x_list[i] = block(x, context = context, hints= hints, audio_scale= audio_scale, multitalk_audio = multitalk_audio, multitalk_masks =multitalk_masks, e= e0,  motion_vec = motion_vec, lynx_ip_embeds= lynx_ip_embeds, lynx_ref_buffer = lynx_ref_buffer, sub_x_no =i,  **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1879, in _call_impl
    return inner()
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1827, in inner
    result = forward_call(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_dynamo\eval_frame.py", line 736, in compile_wrapper
    return fn(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\models\wan\modules\model.py", line 621, in forward
    x_mod = self.norm1(x)
  File "C:\Wan2GP\wan2gp\models\wan\modules\model.py", line 621, in torch_dynamo_resume_in_forward_at_621
    x_mod = self.norm1(x)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_dynamo\eval_frame.py", line 929, in _fn
    return fn(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_functorch\aot_autograd.py", line 1241, in forward
    return compiled_fn(full_args)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 384, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 750, in inner_fn
    outs = compiled_fn(args)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 556, in wrapper
    return compiled_fn(runtime_args)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\output_code.py", line 584, in __call__
    return self.current_callable(inputs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\utils.py", line 2716, in run
    out = model(new_inputs)
  File "C:\Users\yousu\AppData\Local\Temp\torchinductor_yousu\37\c37domnxmme3vbdurcauo7xqxskvgyq6as6hkxfn6w2ydeayoo7a.py", line 97, in call
    triton_poi_fused_add_mul_0.run(arg0_1, arg1_1, arg2_1, buf0, arg0_1, 293529600, stream=stream0)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1133, in run
    self.autotune_to_one_config(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 960, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 934, in benchmark_all_configs
    timings = {
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 935, in <dictcomp>
    launcher: self.bench(launcher, *args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 780, in bench
    cpu_copies = self.copy_args_to_cpu_if_needed(*args, **kwargs)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 847, in copy_args_to_cpu_if_needed
    maybe_copy(name, arg)
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 831, in maybe_copy
    cpu_arg = torch.empty_strided(
  File "C:\Wan2GP\wan2gp\python_embeded\lib\site-packages\torch\utils\_device.py", line 103, in __torch_function__
    return func(*args, **kwargs)
torch.AcceleratorError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions

**Comment by Redtash1** [comment]
What version of WanGP are you on? What model are you using with all settings? Do you have Pytorch compilation ON (Compile Transformer) turned on? Do you have Notification Sound enabled? Thank you.

**Comment by githubnoobb** [comment]
I tried GPU profile 2, 4 and 5. Wan I2V, 720p used to work fine at 81 frames and 8 steps, now 720p fails on the first generation, and 480p gives OOM errors after a small batch of generations. I have removed paligenesis after reading the controversies, so thanks for the heads up.

Teacache and magcache disabled. Two accelerator loras: 
1. Wan_2_2_I2V_A14B_HIGH_lightx2v_MoE_distill_lora_rank_64_bf16
2. Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16

**JSON:**

{
    "attention_mode": "sage2",
    "transformer_types": [
        "i2v_2_2",
        "qwen_image_edit_plus_20B"
    ],
    "text_encoder_quantization": "int8",
    "save_path": "outputs",
    "image_save_path": "outputs",
    "compile": "transformer",
    "profile": 2,
    "vae_config": 0,
    "vae_precision": "16",
    "mixed_precision": "0",
    "metadata_type": "metadata",
    "transformer_quantization": "int8",
    "transformer_dtype_policy": "",
    "boost": 1,
    "clear_file_list": 0,
    "preload_model_policy": [],
    "UI_theme": "gradio",
    "fit_canvas": 0,
    "enhancer_enabled": 0,
    "enhancer_mode": 0,
    "mmaudio_enabled": 0,
    "preload_in_VRAM": 0,
    "depth_anything_v2_variant": "vitl",
    "notification_sound_enabled": 0,
    "notification_sound_volume": 50,
    "max_frames_multiplier": 1,
    "display_stats": 1,
    "video_output_codec": "libx265_28",
    "image_output_codec": "jpeg_95",
    "audio_output_codec": "aac_128",
    "model_hierarchy_type": 1,
    "checkpoints_paths": [
        "ckpts",
        "."
    ],
    "queue_color_scheme": "pastel",
    "embed_source_images": false,
    "video_container": "mp4",
    "last_model_type": "i2v_2_2",
    "last_model_per_family": {
        "wan2_2": "i2v_2_2"
    },
    "last_model_per_type": {
        "i2v_2_2": "i2v_2_2"
    },
    "last_advanced_choice": true,
    "last_resolution_choice": "1104x832",
    "last_resolution_per_group": {
        "720p": "1104x832"
    },
    "enabled_plugins": []

**Comment by Redtash1** [comment]
Try updating DPM made big changes to Wan2GP.

**Comment by githubnoobb** [comment]
Sorry for sending the wrong file, also are you referring to the DPM scheduler or something else? Here is the json file below.

[Driving.json](https://github.com/user-attachments/files/23061126/Driving.json)

**Comment by githubnoobb** [comment]
"The generation of the video has encountered an error: it is likely that you have unsufficient RAM and / or Reserved RAM allocation should be reduced using 'perc_reserved_mem_max' or using a different Profile."

**Comment by Redtash1** [comment]
I see according to this .json that in "Advanced Mode" "Misc" "Override Memory Profile" you have it set to "Profile 2" set it to "Default Memory Profile" and also in "Configuration Tab" "Performance" "Memory Profile (Advanced)" and set it to Profile 4" save settings then close everything and restart. I'll test your Driving.json. Would also send me the image you are using? Thank you.

<img width="822" height="862" alt="Image" src="https://github.com/user-attachments/assets/5dda2b99-60f0-4428-a1eb-39cf1d40f926" />

**Comment by Redtash1** [comment]
Ok. A easier way is to download my v1.0.2. Copy the Install_Wan2GP_Torch_2.7.1+cu128.bat and paste it in your current Wan2GP, then delete the python_embeded folder in current working Wan2GP and then copy the python_embeded from the v1.0.2 you download and paste it in the folder where you deleted the other python_embeded and then double click the 
Install_Wan2GP_Torch_2.7.1+cu128.bat and it will install everything for you but use torch2.7.1+cu128 and you will be back to the old setup that worked correctly. Thank you.

**Comment by Redtash1** [comment]
I can create a new Install.bat using Torch2.9.0+cu128.

**Comment by githubnoobb** [comment]
> Ok. A easier way is to download my v1.0.2. Copy the Install_Wan2GP_Torch_2.7.1+cu128.bat and paste it in your current Wan2GP, then delete the python_embeded folder in current working Wan2GP and then copy the python_embeded from the v1.0.2 you download and paste it in the folder where you deleted the other python_embeded and then double click the Install_Wan2GP_Torch_2.7.1+cu128.bat and it will install everything for you but use torch2.7.1+cu128 and you will be back to the old setup that worked correctly. Thank you.

Thanks this worked, I just had to disable "Compile Transformer Model" and the memory leak issues and OOM errors disappeared. Performance has returned to normal and I can use Profile 2 again with sage2.

What will the new install.bat do? Have you discovered a bug? :)

**Comment by Redtash1** [comment]
Kuul. Glad it's working normal again. Keep the python_embeded, so if you want/need to redo Torch, etc... you will have it. No I didn't found a bug but all I changed was Torch2.7.1 to Torch 2.8.0, Sage and Triton. So the only thing, which can happen, is different Torch version can cause problems and/or be slower. So since you went back to Torch2.7.1 and it's working fine, your GPU must not like Torch2.8.0. The new Install.bat with Torch2.9.0 would just be to see if Torch2.8.0 was the problem which it looks like it was since you switch back to Torch2.7.1 and it's working correctly.

**Comment by Redtash1** [comment]
I did confirm your Memory errors. Torch 2.8.0 is 1.5GB bigger than Torch 2.7.1. But I noticed after video generation is finished that 2.8.0 don't release the system ram back to when the models are fully loaded which is about 48GB ish but keeps it about 60GB ish until about 1/2 through the next video generation but then it only releases about 7ish instead of about 13GB and with each video generation it releases less and less Ram. But Torch 2.7.1 doesn't have that problem. Idk why that is, I guess I'll mention it to DeepBeepMeep and see what he says.

**Comment by Redtash1** [comment]
Thank you for finding it.
